apiVersion: v1
kind: Service
metadata:
  name: device-monitor-svc
spec:
  selector:
    app: device-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
